name: Community Maps
markdown: redcarpet
highlighter: pygments
permalink: /blog/:year/:month/:day/:title.html
url: /opencommunitymaps/

redcarpet:
  extensions: ['tables']

collections:
  help:
    output: true
  docs:
    output: true