name: GeoKey
highlighter: rouge
permalink: /blog/:year/:title.html
exclude: ['Gruntfile.js', 'package.json', 'node_modules']

redcarpet:
  extensions: ['tables', 'with_toc_data']

collections:
  help:
    output: true
  docs:
    output: true
  extensions:
    output: true
